ARG GO_VERSION
FROM --platform=$BUILDPLATFORM docker.io/library/golang:${GO_VERSION} AS builder

WORKDIR /src

COPY . /src

# Build
ARG TARGETOS TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a -ldflags="-s -w" -o /out/onionbalance-local-manager ./agents/onionbalance/main.go

# package build
FROM docker.io/library/alpine:3.22

ARG OB_VERSION="0.2.4"

RUN apk add --no-cache --update \
    git \
    py3-cryptography \
    py3-pip \
    py3-pycryptodomex \
    py3-setproctitle \
    py3-wheel \
    && python3 -m pip install --no-cache-dir git+https://gitlab.torproject.org/tpo/core/onionbalance.git@${OB_VERSION}

WORKDIR /app
COPY --from=builder /out/onionbalance-local-manager /app

USER 1001

ENTRYPOINT ["/app/onionbalance-local-manager"]
