ARG GO_VERSION
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.24 AS builder

WORKDIR /src

COPY . /src

# Build
ARG TARGETOS TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a -ldflags="-s -w" -o /out/tor-local-manager ./agents/tor/main.go

FROM ghcr.io/rgst-io/tor-controller/tor AS tor
COPY --from=builder --chmod=0555 /out/tor-local-manager /usr/bin/
ENTRYPOINT ["/app/tor-local-manager"]
